// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyD7RpTwT8cAvHpQwLxCrTDazao7Ou1anLc",
      authDomain: "tasklist-b01ae.firebaseapp.com",
      projectId: "tasklist-b01ae",
      storageBucket: "tasklist-b01ae.appspot.com",
      messagingSenderId: "46802841767",
      appId: "1:46802841767:web:5ad034404123349c64eb82"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDml-vBy_OkzcfH83pw0YPz1kc-QYWtFcE',
    appId: '1:46802841767:android:3b79e248cd487f1664eb82',
    messagingSenderId: '46802841767',
    projectId: 'tasklist-b01ae',
    storageBucket: 'tasklist-b01ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiQdXjfEA7UwdDsofNF7_iEw_Z8Pgy4I',
    appId: '1:46802841767:ios:4e30d1d76caa1c8264eb82',
    messagingSenderId: '46802841767',
    projectId: 'tasklist-b01ae',
    storageBucket: 'tasklist-b01ae.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNiQdXjfEA7UwdDsofNF7_iEw_Z8Pgy4I',
    appId: '1:46802841767:ios:18e9d36e9d8b639a64eb82',
    messagingSenderId: '46802841767',
    projectId: 'tasklist-b01ae',
    storageBucket: 'tasklist-b01ae.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
